export const fetchBreedListFixture = {
  message: {
    affenpinscher: [],
    african: [],
    airedale: [],
    akita: [],
    appenzeller: [],
    australian: ['shepherd'],
    basenji: [],
    beagle: [],
    bluetick: [],
    borzoi: [],
    bouvier: [],
    boxer: [],
    brabancon: [],
    briard: [],
    buhund: ['norwegian'],
    bulldog: ['boston', 'english', 'french'],
    bullterrier: ['staffordshire'],
    cattledog: ['australian'],
    chihuahua: [],
    chow: [],
    clumber: [],
    cockapoo: [],
    collie: ['border'],
    coonhound: [],
    corgi: ['cardigan'],
    cotondetulear: [],
    dachshund: [],
    dalmatian: [],
    dane: ['great'],
    deerhound: ['scottish'],
    dhole: [],
    dingo: [],
    doberman: [],
    elkhound: ['norwegian'],
    entlebucher: [],
    eskimo: [],
    finnish: ['lapphund'],
    frise: ['bichon'],
    germanshepherd: [],
    greyhound: ['italian'],
    groenendael: [],
    havanese: [],
    hound: ['afghan', 'basset', 'blood', 'english', 'ibizan', 'plott', 'walker'],
    husky: [],
    keeshond: [],
    kelpie: [],
    komondor: [],
    kuvasz: [],
    labradoodle: [],
    labrador: [],
    leonberg: [],
    lhasa: [],
    malamute: [],
    malinois: [],
    maltese: [],
    mastiff: ['bull', 'english', 'tibetan'],
    mexicanhairless: [],
    mix: [],
    mountain: ['bernese', 'swiss'],
    newfoundland: [],
    otterhound: [],
    ovcharka: ['caucasian'],
    papillon: [],
    pekinese: [],
    pembroke: [],
    pinscher: ['miniature'],
    pitbull: [],
    pointer: ['german', 'germanlonghair'],
    pomeranian: [],
    poodle: ['miniature', 'standard', 'toy'],
    pug: [],
    puggle: [],
    pyrenees: [],
    redbone: [],
    retriever: ['chesapeake', 'curly', 'flatcoated', 'golden'],
    ridgeback: ['rhodesian'],
    rottweiler: [],
    saluki: [],
    samoyed: [],
    schipperke: [],
    schnauzer: ['giant', 'miniature'],
    setter: ['english', 'gordon', 'irish'],
    sheepdog: ['english', 'shetland'],
    shiba: [],
    shihtzu: [],
    spaniel: ['blenheim', 'brittany', 'cocker', 'irish', 'japanese', 'sussex', 'welsh'],
    springer: ['english'],
    stbernard: [],
    terrier: [
      'american',
      'australian',
      'bedlington',
      'border',
      'cairn',
      'dandie',
      'fox',
      'irish',
      'kerryblue',
      'lakeland',
      'norfolk',
      'norwich',
      'patterdale',
      'russell',
      'scottish',
      'sealyham',
      'silky',
      'tibetan',
      'toy',
      'welsh',
      'westhighland',
      'wheaten',
      'yorkshire'
    ],
    tervuren: [],
    vizsla: [],
    waterdog: ['spanish'],
    weimaraner: [],
    whippet: [],
    wolfhound: ['irish']
  },
  status: 'success'
};
export const breedListFixture = [
  { id: 'affenpinscher', name: 'affenpinscher' },
  { id: 'african', name: 'african' },
  { id: 'airedale', name: 'airedale' },
  { id: 'akita', name: 'akita' },
  { id: 'appenzeller', name: 'appenzeller' },
  { id: 'australian/shepherd', name: 'australian (shepherd)' },
  { id: 'basenji', name: 'basenji' },
  { id: 'beagle', name: 'beagle' },
  { id: 'bluetick', name: 'bluetick' },
  { id: 'borzoi', name: 'borzoi' },
  { id: 'bouvier', name: 'bouvier' },
  { id: 'boxer', name: 'boxer' },
  { id: 'brabancon', name: 'brabancon' },
  { id: 'briard', name: 'briard' },
  { id: 'buhund/norwegian', name: 'buhund (norwegian)' },
  { id: 'bulldog/boston', name: 'bulldog (boston)' },
  { id: 'bulldog/english', name: 'bulldog (english)' },
  { id: 'bulldog/french', name: 'bulldog (french)' },
  { id: 'bullterrier/staffordshire', name: 'bullterrier (staffordshire)' },
  { id: 'cattledog/australian', name: 'cattledog (australian)' },
  { id: 'chihuahua', name: 'chihuahua' },
  { id: 'chow', name: 'chow' },
  { id: 'clumber', name: 'clumber' },
  { id: 'cockapoo', name: 'cockapoo' },
  { id: 'collie/border', name: 'collie (border)' },
  { id: 'coonhound', name: 'coonhound' },
  { id: 'corgi/cardigan', name: 'corgi (cardigan)' },
  { id: 'cotondetulear', name: 'cotondetulear' },
  { id: 'dachshund', name: 'dachshund' },
  { id: 'dalmatian', name: 'dalmatian' },
  { id: 'dane/great', name: 'dane (great)' },
  { id: 'deerhound/scottish', name: 'deerhound (scottish)' },
  { id: 'dhole', name: 'dhole' },
  { id: 'dingo', name: 'dingo' },
  { id: 'doberman', name: 'doberman' },
  { id: 'elkhound/norwegian', name: 'elkhound (norwegian)' },
  { id: 'entlebucher', name: 'entlebucher' },
  { id: 'eskimo', name: 'eskimo' },
  { id: 'finnish/lapphund', name: 'finnish (lapphund)' },
  { id: 'frise/bichon', name: 'frise (bichon)' },
  { id: 'germanshepherd', name: 'germanshepherd' },
  { id: 'greyhound/italian', name: 'greyhound (italian)' },
  { id: 'groenendael', name: 'groenendael' },
  { id: 'havanese', name: 'havanese' },
  { id: 'hound/afghan', name: 'hound (afghan)' },
  { id: 'hound/basset', name: 'hound (basset)' },
  { id: 'hound/blood', name: 'hound (blood)' },
  { id: 'hound/english', name: 'hound (english)' },
  { id: 'hound/ibizan', name: 'hound (ibizan)' },
  { id: 'hound/plott', name: 'hound (plott)' },
  { id: 'hound/walker', name: 'hound (walker)' },
  { id: 'husky', name: 'husky' },
  { id: 'keeshond', name: 'keeshond' },
  { id: 'kelpie', name: 'kelpie' },
  { id: 'komondor', name: 'komondor' },
  { id: 'kuvasz', name: 'kuvasz' },
  { id: 'labradoodle', name: 'labradoodle' },
  { id: 'labrador', name: 'labrador' },
  { id: 'leonberg', name: 'leonberg' },
  { id: 'lhasa', name: 'lhasa' },
  { id: 'malamute', name: 'malamute' },
  { id: 'malinois', name: 'malinois' },
  { id: 'maltese', name: 'maltese' },
  { id: 'mastiff/bull', name: 'mastiff (bull)' },
  { id: 'mastiff/english', name: 'mastiff (english)' },
  { id: 'mastiff/tibetan', name: 'mastiff (tibetan)' },
  { id: 'mexicanhairless', name: 'mexicanhairless' },
  { id: 'mix', name: 'mix' },
  { id: 'mountain/bernese', name: 'mountain (bernese)' },
  { id: 'mountain/swiss', name: 'mountain (swiss)' },
  { id: 'newfoundland', name: 'newfoundland' },
  { id: 'otterhound', name: 'otterhound' },
  { id: 'ovcharka/caucasian', name: 'ovcharka (caucasian)' },
  { id: 'papillon', name: 'papillon' },
  { id: 'pekinese', name: 'pekinese' },
  { id: 'pembroke', name: 'pembroke' },
  { id: 'pinscher/miniature', name: 'pinscher (miniature)' },
  { id: 'pitbull', name: 'pitbull' },
  { id: 'pointer/german', name: 'pointer (german)' },
  { id: 'pointer/germanlonghair', name: 'pointer (germanlonghair)' },
  { id: 'pomeranian', name: 'pomeranian' },
  { id: 'poodle/miniature', name: 'poodle (miniature)' },
  { id: 'poodle/standard', name: 'poodle (standard)' },
  { id: 'poodle/toy', name: 'poodle (toy)' },
  { id: 'pug', name: 'pug' },
  { id: 'puggle', name: 'puggle' },
  { id: 'pyrenees', name: 'pyrenees' },
  { id: 'redbone', name: 'redbone' },
  { id: 'retriever/chesapeake', name: 'retriever (chesapeake)' },
  { id: 'retriever/curly', name: 'retriever (curly)' },
  { id: 'retriever/flatcoated', name: 'retriever (flatcoated)' },
  { id: 'retriever/golden', name: 'retriever (golden)' },
  { id: 'ridgeback/rhodesian', name: 'ridgeback (rhodesian)' },
  { id: 'rottweiler', name: 'rottweiler' },
  { id: 'saluki', name: 'saluki' },
  { id: 'samoyed', name: 'samoyed' },
  { id: 'schipperke', name: 'schipperke' },
  { id: 'schnauzer/giant', name: 'schnauzer (giant)' },
  { id: 'schnauzer/miniature', name: 'schnauzer (miniature)' },
  { id: 'setter/english', name: 'setter (english)' },
  { id: 'setter/gordon', name: 'setter (gordon)' },
  { id: 'setter/irish', name: 'setter (irish)' },
  { id: 'sheepdog/english', name: 'sheepdog (english)' },
  { id: 'sheepdog/shetland', name: 'sheepdog (shetland)' },
  { id: 'shiba', name: 'shiba' },
  { id: 'shihtzu', name: 'shihtzu' },
  { id: 'spaniel/blenheim', name: 'spaniel (blenheim)' },
  { id: 'spaniel/brittany', name: 'spaniel (brittany)' },
  { id: 'spaniel/cocker', name: 'spaniel (cocker)' },
  { id: 'spaniel/irish', name: 'spaniel (irish)' },
  { id: 'spaniel/japanese', name: 'spaniel (japanese)' },
  { id: 'spaniel/sussex', name: 'spaniel (sussex)' },
  { id: 'spaniel/welsh', name: 'spaniel (welsh)' },
  { id: 'springer/english', name: 'springer (english)' },
  { id: 'stbernard', name: 'stbernard' },
  { id: 'terrier/american', name: 'terrier (american)' },
  { id: 'terrier/australian', name: 'terrier (australian)' },
  { id: 'terrier/bedlington', name: 'terrier (bedlington)' },
  { id: 'terrier/border', name: 'terrier (border)' },
  { id: 'terrier/cairn', name: 'terrier (cairn)' },
  { id: 'terrier/dandie', name: 'terrier (dandie)' },
  { id: 'terrier/fox', name: 'terrier (fox)' },
  { id: 'terrier/irish', name: 'terrier (irish)' },
  { id: 'terrier/kerryblue', name: 'terrier (kerryblue)' },
  { id: 'terrier/lakeland', name: 'terrier (lakeland)' },
  { id: 'terrier/norfolk', name: 'terrier (norfolk)' },
  { id: 'terrier/norwich', name: 'terrier (norwich)' },
  { id: 'terrier/patterdale', name: 'terrier (patterdale)' },
  { id: 'terrier/russell', name: 'terrier (russell)' },
  { id: 'terrier/scottish', name: 'terrier (scottish)' },
  { id: 'terrier/sealyham', name: 'terrier (sealyham)' },
  { id: 'terrier/silky', name: 'terrier (silky)' },
  { id: 'terrier/tibetan', name: 'terrier (tibetan)' },
  { id: 'terrier/toy', name: 'terrier (toy)' },
  { id: 'terrier/welsh', name: 'terrier (welsh)' },
  { id: 'terrier/westhighland', name: 'terrier (westhighland)' },
  { id: 'terrier/wheaten', name: 'terrier (wheaten)' },
  { id: 'terrier/yorkshire', name: 'terrier (yorkshire)' },
  { id: 'tervuren', name: 'tervuren' },
  { id: 'vizsla', name: 'vizsla' },
  { id: 'waterdog/spanish', name: 'waterdog (spanish)' },
  { id: 'weimaraner', name: 'weimaraner' },
  { id: 'whippet', name: 'whippet' },
  { id: 'wolfhound/irish', name: 'wolfhound (irish)' }
];
